### PR TITLE
docs: Add INSTALL Document

### PR DESCRIPTION
**Pull request by SuperRedTrain**
An INSTALL document is required for our project.
issue #22

### CODE REVIEW

**Review by yu-zha — APPROVED** [review]
It basically covers most of the dependency we will use, with some dev Dependency probably added later for testing purposes.

**Review by kindubadhan — APPROVED** [review]
This install document almost describes all libraries and packages that we need to install in our project with the commands which is very helpful.

**Review by London-Alex — CHANGES_REQUESTED** [review]
It seems to be missing details for the concurrently and react-router-dom dependencies. Otherwise, it looks good.

**Comment by Sandraxyz** [comment]
it look good, it includes all the "installs" we need.

**Pull request merged**
