### PR TITLE
docs: Add .gitignore file

### PR DESCRIPTION
**Pull request by SuperRedTrain**
This .gitignore file is not completed now. Updates will be added in the future.

### CODE REVIEW

**Review by kindubadhan — APPROVED** [review]
Thanks for this .gitignore file. It will be very helpful in future for our project data.

**Review by yu-zha — APPROVED** [review]
The.gitignore file is good enough as far as we're concerned, but we'll keep updating it as we go along.

**Review by London-Alex — APPROVED** [review]
Looks good.

**Review by yu-zha — APPROVED** [review]
Great! Good catch, Alex.

**Review by Sandraxyz — APPROVED** [review]
I guess it looks good like this to me too! thank you for adding it @SuperRedTrain

**Pull request merged**
