### PR TITLE
impl:Setup The Project Structure

### PR DESCRIPTION
**Pull request by Sandraxyz**
I created the structure of project based on model of youtube tutorial we referred to by Beau Carnes from FreeCodeCamp.org
youtube link: https://www.youtube.com/watch?v=mrHNSanmqQ4
github link: https://github.com/beaucarnes/restaurant-reviews
issue #19

### CODE REVIEW

**Comment by Sandraxyz** [comment]
The frontend folder is for the client, and the backend folder is for the server.

**Review by yu-zha — APPROVED** [review]
The API directory contains the code of router file, gets the request, and responds to the interface. When we starting the server, make sure the database and frontend are connected with the backend.

**Review by kindubadhan — APPROVED** [review]
Service Directory is used to import a library Axios for Get request, Put request, Post request and Delete request. This axios package should be set up in a helper file like https-common. This directory is used to make API calls and also return information from API calls.

**Review by London-Alex — APPROVED** [review]
Components:
The components directory contains the JavaScript component files. Each of these components represents a page or a section of a page. A component file itself contains the HTML for the page as well as the JavaScript functions necessary to load the page's data and handle user input. A component can be something like a product page, but it can also be a reusable feature like a toolbar, navigation menu, or sidebar.

**Comment by SuperRedTrain** [comment]
The dao directory in the backend folder contains JavaScript files for data access objects. These files allow us manage the connection with the data source to obtain and store data. The data source can be database / xml or any other storage mechanism.

**Review by SuperRedTrain — APPROVED** [review]

**Pull request merged**
