### PR TITLE
Add the code review checklist first version

### PR DESCRIPTION
**Pull request by yu-zha**
I just updated some of my idea for the Code Review Checklist which is missing in our GitHub flow assignment. Feel free to edit your thought! Thanks!

### CODE REVIEW

**Comment by London-Alex** [comment]
Looks good to me.

**Review by London-Alex — APPROVED** [review]

**Comment by SuperRedTrain** [comment]
It looked good to me

**Review by kindubadhan — COMMENTED** [review]
Code review checklist looks perfect

**Review by SuperRedTrain — COMMENTED** [review]
Looks good to me.

**Pull request merged**
