### PR TITLE
impl: Product Detail Page and Products in Home Screen

### PR DESCRIPTION
**Pull request by London-Alex**
This pull request implements functionality for displaying and accessing products on the website. When a user loads the home page, they will now see a collection of the products with their title, price, and image. Clicking one of these product cards will lead the user to that product's product detail page. The product detail page displays the product's title, image, price, description, category, stock, and the seller's username. It also shows the Add to Cart button previously implemented by Ke. The Current Stock section of the product detail page will display an Out of Stock! message is the product quantity is less than one.

Also in this pull request is a small adjustment to the image uploads. In order for the frontend to display the uploaded images, they needed to be store in frontend/public, while they had previously been stored in backend/. The uploads folder has been moved to frontend/public and some logic in uploads.controller.js was changed slightly so that images will be saved there instead.

GitHub Issue #60

### CODE REVIEW

**Review by yu-zha — APPROVED** [review]
Great job!
I tested uploading a new product, after that, I can see the product from the homepage.
After clicking the picture from the homepage, it will redirect to a new page with more detailed information and a button to add to the shopping cart.

**Review by SuperRedTrain — CHANGES_REQUESTED** [review]
Everything works well. There is only one suggestion: It shows a warning on the console: "Warning: Each child in a list should have a unique "key" prop." Could you please add key={product.title} into "<Image src={product.image} alt={product.title} fluid>" in ProductList.js. Then I will approve the PR.

**Comment by London-Alex** [comment]
@SuperRedTrain Thank you for the suggestion! I've made that change. I actually had to put it in the outermost div to make it resolve the warning.

**Review by SuperRedTrain — APPROVED** [review]
This PR appropriately labelled and has detailed description in the first comment. It also has the  appropriate issue linked. I tested this branch on my local machine and every function works correct. Thank you for your work.

**Pull request merged**
